export { default as Hero } from './Hero'
export { default as Section } from './Section'
export { default as Services} from './Services'
export { default as ServiceItem} from './ServiceItem'
export { default as About} from './About'
export { default as Footer} from './Footer'
export { default as Works} from './Works'
export { default as WorkItem} from './WorkItem'
